set(NOVACOIN_CORE_SOURCES
    src/block.cpp
    src/blockchain.cpp
    src/transaction.cpp
    src/consensus/chain_params.cpp
    src/core/build_info.cpp
    src/mempool/policy.cpp
    src/network/peer_manager.cpp
    src/network/p2p_node.cpp
    src/network/p2p_protocol.cpp
    src/network/seed_registry.cpp
    src/rpc/rpc_context.cpp
    src/rpc/rpc_dispatcher.cpp
    src/rpc/rpc_server.cpp
    src/rpc/rpc_types.cpp
    src/storage/block_storage.cpp
    src/storage/chain_snapshot.cpp
    src/utils/logger.cpp
    src/validation/block_validator.cpp
    src/wallet/wallet.cpp
    src/wallet/wallet_dat_codec.cpp
    src/wallet/wallet_dat_loader.cpp
    src/wallet/wallet_dat_writer.cpp
    src/wallet/wallet_profile.cpp
)

set(NOVACOIN_APP_SOURCES
    src/main.cpp
    src/apps/novacoin-tx.cpp
    src/apps/novacoin-wallet.cpp
    src/apps/novacoin-cli.cpp
    src/apps/novacoind.cpp
    src/apps/novacoin-regtest.cpp
)
